title: Erweiterung einer REST-API
subtitle: Für die Webanwendung Holistic Project Tracking um eine Announcement-Funktion
name: Thomas Abel
author: Thomas Abel
version: 0.0.1
quarto-required: ">=1.3.0"
company: holistic-net GmbH
company-logo: ./images/holistic_logo_row.png
ihk-header: Präsentation zur betrieblichen Projektarbeit
ihk-logo: ./images/ihk_logo.jpg
lang: de
date: today
date-format: "DD. MM. YYYY"
format:
  revealjs:
    theme: [default, holistic-theme.scss]
    # logo: ./images/holistic_logo_row.png
    slide-number: true
    show-slide-number: all 
    embed-resources: true
    highlight-style: github
    template-partials:
      - title-slide.html
    title-slide-attributes:
      data-background-color: "#fefbf8"
    footer: "{{< meta date >}} | © {{< meta name >}}"
  # html:
  #   toc: true
  #   html-math-method: katex
  #   css: styles.css
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  # ihk-presentation-revealjs: 
  #   footer: "{{< meta title >}} | {{< meta date >}} | © {{< meta name >}}"
toc: false