title: Erweiterung einer REST-API
subtitle: Für die Webanwendung Holistic Project Tracking um eine Announcement-Funktion
author: Thomas Abel
# institute: holistic-net GmbH
date: today
date-format: "DD. MM. YYYY"
version: 0.0.1
quarto-required: ">=1.3.0"
name: Thomas Abel
company: holistic-net GmbH
company-logo: ./images/holistic_logo_row.png
ihk-header: Präsentation zur betrieblichen Projektarbeit
ihk-logo: ./images/ihk_logo.jpg
toc-img: ./images/toc.svg
lang: de
format:
  revealjs:
    # theme: white
    toc: true
    toc-title: Ablauf
    toc-depth: 1
    theme: [default, holistic-theme.scss]
    # logo: ./images/holistic_logo_row.png
    width: 1050
    height: 700
    margin: 0.2
    transition: fade
    auto-animate: true
    slide-number: true
    show-slide-number: all 
    embed-resources: true
    highlight-style: github
    template-partials:
      - title-slide.html
      - toc-slide.html
    title-slide-attributes:
      data-background-color: "#fefbf8"
    # include-after-body: toc-fragments.js