title: Erweiterung einer REST-API
subtitle: Für die Webanwendung ‚‚holistic project tracking‘‘ um eine Ankündigungs-Funktion
author: Thomas Abel
date: today
date-format: "DD. MM. YYYY"
version: 0.0.1
quarto-required: ">=1.3.0"
name: Thomas Abel
company: holistic-net GmbH
company-logo: ./images/holistic-net/holistic-net-logo-text.svg
company-logo-footer: ./images/holistic-net/holistic_logo_footer.png
ihk-header: Präsentation zur betrieblichen Projektarbeit
ihk-logo: ./images/ihk/ihk_logo.jpg
toc-img: ./images/title-svgs/toc.svg
lang: de
execute:
  freeze: auto
format:
  # # ------------------> HTML <----------------
  # html:
  #   # theme: [default, holistic-theme.scss]
  #   toc: true
  # ------------------> Beamer <----------------
  # beamer:
  #   # theme: [default, holistic-theme.scss]
  #   toc: true
  # ------------------> reveal <----------------
  revealjs:
    # theme: white
    toc: true
    toc-title: Ablauf
    toc-depth: 1
    theme: [default, holistic-theme.scss]
    transition: none
    auto-animate: true
    slide-number: true
    show-slide-number: all 
    embed-resources: true
    highlight-style: github
    template-partials:
      - title-slide.html
      - toc-slide.html
    title-slide-attributes:
      data-background-color: "#fefbf8"
    logo: ./images/holistic-net/holistic_logo_footer.png
    footer: '© {{<meta name>}}'